require:
  - rubocop-rake
  - rubocop-rspec

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'spec/**/*.rb'

AllCops:
  Exclude:
    - 'script.rb'
    - 'vendor/bundle/**/*'
  NewCops: enable